<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="Identifiers.fs" />
    <Compile Include="Paths.fs" />
    <Compile Include="Operations.fs" />
    <Compile Include="Providers.fs" />
  </ItemGroup>
  <ItemGroup>
    <Content Include="*.fsproj; *.fs" PackagePath="fable\" />
  </ItemGroup>
</Project>
